<a href="https://colab.research.google.com/github/siddhartha-sai-17/Data-visualisation/blob/main/Numpy_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr_1d = np.array([1,2,3])
print(arr_1d)

[1 2 3]


In [ ]:

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [ ]:
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


In [ ]:
#zeros

In [ ]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#ones

In [ ]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#random values

In [ ]:
import numpy as np

random_arr = np.random.random((2, 2))
print(random_arr)


[[0.6284316  0.73585026]
 [0.96149128 0.4782    ]]


In [ ]:
#identity matrix

In [ ]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Array with a range of values

In [ ]:
range_arr = np.arange(0,10,2)
print(range_arr)

[0 2 4 6 8]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
print("Shape:",arr.shape)

Shape: (2, 3)


In [ ]:
print("Size:",arr.size)

Size: 6


In [ ]:
print("Data type:",arr.dtype)

Data type: int64


In [ ]:
print("Number of Dimensions:",arr.ndim)

Number of Dimensions: 2


In [ ]:
#question 1

In [ ]:
temp_data = np.array([[1,2,3],[4,5,6]])

In [ ]:
print(temp_data)

[[1 2 3]
 [4 5 6]]


In [ ]:
print("Shape:",temp_data.shape)

Shape: (2, 3)


In [ ]:
print("Size:",temp_data.size)

Size: 6


In [ ]:
print("Data type:",temp_data.dtype)

Data type: int64


In [ ]:
print("Number of dimensios:",temp_data.ndim)

Number of dimensios: 2


In [ ]:
gh_3 = np.array([21,23,22])

In [ ]:
new_updated_temp_data = np.vstack((temp_data,gh_3))

In [ ]:
sensor_error_flag = np.zeros((2,3))

In [ ]:
print(sensor_error_flag)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
greenhouse_identity = np.ones((3,3))

In [ ]:
print(new_updated_temp_data)
print(sensor_error_flag)
print(greenhouse_identity)

[[ 1  2  3]
 [ 4  5  6]
 [21 23 22]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#indexing and slicing

In [ ]:
#slicig in python means taking elements from on given index to another index

Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.

The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array

Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.


> Add blockquote



In [ ]:
import numpy as np

# Rows → Apples, Oranges
# Columns → Mon, Tue, Wed, Thu, Fri, Sat, Sun
shipments = np.array([
    [50, 60, 55, 70, 65, 80, 90],  # Apples
    [40, 45, 50, 60, 55, 70, 75]   # Oranges
])

print("Shipments array:\n", shipments)


Shipments array:
 [[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]


In [ ]:
wed_apple = shipments[0,2]
print(wed_apple)

55


In [ ]:
sun_orange = shipments[1,6]
print(sun_orange)

75


In [ ]:
weekday_shipments = shipments[:, 0:5]
print("\nWeekday shipments (Mon–Fri):\n", weekday_shipments)
weekend_shipments = shipments[:, 5:7]
print("\nWeekend shipments (Sat & Sun):\n", weekend_shipments)
apples_wed_to_sat = shipments[0, 2:6]
print("\nApples (Wed–Sat):", apples_wed_to_sat)



Weekday shipments (Mon–Fri):
 [[50 60 55 70 65]
 [40 45 50 60 55]]

Weekend shipments (Sat & Sun):
 [[80 90]
 [70 75]]

Apples (Wed–Sat): [55 70 65 80]


In [ ]:
shipments[0,5] = 100
print("updated shipments",shipments)

updated shipments [[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [ ]:
#operations on arrays

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])


In [ ]:
print(a+b) #element - wise addition

[5 7 9]


In [ ]:
print(a*b) #element - wise multiplication

[ 4 10 18]


In [ ]:
print(a*2) #Scalalr operations

[2 4 6]


In [ ]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
result = np.dot(mat1,mat2)
print(result)

[[19 22]
 [43 50]]


In [ ]:
#broadcasting

In [ ]:
a = np.array([1,2,3])
b = 2
print(a+b)

[3 4 5]


In [ ]:
#universal functions

In [ ]:
x = np.array([1,2,3])

In [ ]:
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081]


In [ ]:
print(np.log(x))

[0.         0.69314718 1.09861229]


In [ ]:
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)

array([ 1.71828183,  6.3890561 , 19.08553692])

In [ ]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125])

In [ ]:
np.log2(x)

array([0.       , 1.       , 1.5849625])

In [ ]:
np.expm1(x)

array([ 1.71828183,  6.3890561 , 19.08553692])

In [ ]:
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)

/tmp/ipython-input-2366013803.py:4: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(x)
/tmp/ipython-input-2366013803.py:5: RuntimeWarning: invalid value encountered in arccos
  np.arccos(x)


array([0.01745329, 0.03490659, 0.05235988])

In [ ]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [ ]:
np.tan(x)

array([ 1.55740772, -2.18503986, -0.14254654])

In [ ]:
np.arcsin(x)

/tmp/ipython-input-1524129805.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(x)


array([1.57079633,        nan,        nan])

In [ ]:
import numpy as np

x = np.array([1, 2, 3])
np.arcsin(x)


/tmp/ipython-input-2688303474.py:4: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(x)


array([1.57079633,        nan,        nan])

In [ ]:
np.arccos(x)

/tmp/ipython-input-396561874.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(x)


array([ 0., nan, nan])

In [ ]:
import numpy as np

farmA = np.array([[10, 12, 11],
                  [9, 14, 13],
                  [15, 16, 14],
                  [11, 12, 13]])

farmB = np.array([[8, 10, 9],
                  [12, 13, 14],
                  [10, 11, 12],
                  [9, 8, 10]])

farmC = np.array([[14, 15, 16],
                  [13, 12, 14],
                  [10, 11, 12],
                  [15, 16, 17]])
production_all = np.stack([farmA, farmB, farmC], axis=0)
print(production_all)
# 3️⃣ Array attributes
print("Shape:", production_all.shape)
print("Size:", production_all.size)
print("Dtype:", production_all.dtype)
print("Dimensions:", production_all.ndim)

# -----------------------------
# 4️⃣ Per-farm totals and stats
total_per_farm = production_all.sum(axis=(1,2))  # sum over panels & hours
mean_per_farm = production_all.mean(axis=(1,2))
std_per_farm = production_all.std(axis=(1,2))
var_per_farm = production_all.var(axis=(1,2))

print("Total per farm:", total_per_farm)
print("Mean per farm:", mean_per_farm)
print("Std per farm:", std_per_farm)
print("Var per farm:", var_per_farm)
hour_weights = np.array([0.5, 1.0, 0.75])
weighted_per_panel = np.dot(production_all, hour_weights)  # shape (3,4)
print("Weighted per panel:\n", weighted_per_panel)




[[[10 12 11]
  [ 9 14 13]
  [15 16 14]
  [11 12 13]]

 [[ 8 10  9]
  [12 13 14]
  [10 11 12]
  [ 9  8 10]]

 [[14 15 16]
  [13 12 14]
  [10 11 12]
  [15 16 17]]]
Shape: (3, 4, 3)
Size: 36
Dtype: int64
Dimensions: 3
Total per farm: [150 126 165]
Mean per farm: [12.5  10.5  13.75]
Std per farm: [1.97905701 1.84842275 2.086664  ]
Var per farm: [3.91666667 3.41666667 4.35416667]
Weighted per panel:
 [[25.25 28.25 34.   27.25]
 [20.75 29.5  25.   20.  ]
 [34.   29.   25.   36.25]]


In [ ]:
total_per_farm = production_all.sum(axis=(1,2))  # shape (3,)
print("Total energy per farm:", total_per_farm)

Total energy per farm: [150 126 165]


In [ ]:
import numpy as np

# -----------------------------
# 1️⃣ Create 2D arrays for each farm (4 panels × 3 hours)
# Sample data (kWh)
farmA = np.array([[10, 12, 11],
                  [9, 14, 13],
                  [15, 16, 14],
                  [11, 12, 13]])

farmB = np.array([[8, 10, 9],
                  [12, 13, 14],
                  [10, 11, 12],
                  [9, 8, 10]])

farmC = np.array([[14, 15, 16],
                  [13, 12, 14],
                  [10, 11, 12],
                  [15, 16, 17]])

# 2️⃣ Stack into 3D array (farms × panels × hours)
production_all = np.stack([farmA, farmB, farmC], axis=0)

# 3️⃣ Array attributes
print("Shape:", production_all.shape)
print("Size:", production_all.size)
print("Dtype:", production_all.dtype)
print("Dimensions:", production_all.ndim)

# -----------------------------
# 4️⃣ Per-farm totals and stats
total_per_farm = production_all.sum(axis=(1,2))  # sum over panels & hours
mean_per_farm = production_all.mean(axis=(1,2))
std_per_farm = production_all.std(axis=(1,2))
var_per_farm = production_all.var(axis=(1,2))

print("Total per farm:", total_per_farm)
print("Mean per farm:", mean_per_farm)
print("Std per farm:", std_per_farm)
print("Var per farm:", var_per_farm)

# -----------------------------
# 5️⃣ Weighted per-panel energy (dot product with hour_weights)
hour_weights = np.array([0.5, 1.0, 0.75])
weighted_per_panel = np.dot(production_all, hour_weights)  # shape (3,4)
print("Weighted per panel:\n", weighted_per_panel)

# -----------------------------
# 6️⃣ Apply broadcasting adjustment (+0.5 kWh for Farm B)
production_all[1] += 0.5  # broadcasting across all panels & hours in Farm B

# -----------------------------
# 7️⃣ Z-score normalization per farm
# reshape mean & std for broadcasting (3,1,1)
mean_reshaped = mean_per_farm[:, np.newaxis, np.newaxis]
std_reshaped = std_per_farm[:, np.newaxis, np.newaxis]

normalized = (production_all - mean_reshaped) / std_reshaped
print("Normalized shape:", normalized.shape)

# -----------------------------
# 8️⃣ Element-wise ufuncs

# Exponential family
exp_data = np.exp(normalized)
expm1_data = np.expm1(normalized)
# np.log requires positive values, normalize to positive domain
log_data = np.log(exp_data)  # safe because exp_data > 0
log10_data = np.log10(exp_data)
log2_data = np.log2(exp_data)

# Trigonometric
sin_data = np.sin(normalized)
cos_data = np.cos(normalized)
tan_data = np.tan(normalized)
arcsin_data = np.arcsin(np.clip(normalized, -1, 1))  # clip to [-1,1]
arccos_data = np.arccos(np.clip(normalized, -1, 1))
arctan_data = np.arctan(normalized)
degrees_data = np.degrees(normalized)
radians_data = np.radians(normalized)

# Rounding
round_data = np.round(normalized, 2)
floor_data = np.floor(normalized)
ceil_data = np.ceil(normalized)
trunc_data = np.trunc(normalized)

# -----------------------------
# 9️⃣ Comparison & logical
high_output = production_all > 20
even_hours_mask = (np.arange(production_all.shape[2]) % 2 == 0)
# broadcast even_hours_mask to panels
even_hours_mask_broadcast = even_hours_mask[np.newaxis, np.newaxis, :]
logical_and_mask = np.logical_and(high_output, even_hours_mask_broadcast)
logical_or_mask = np.logical_or(high_output, even_hours_mask_broadcast)
logical_not_mask = np.logical_not(high_output)
logical_xor_mask = np.logical_xor(high_output, even_hours_mask_broadcast)

# -----------------------------
# 10️⃣ Bitwise operations (integer array)
alerts = np.array([[1,0,1],
                   [0,0,1],
                   [1,1,0],
                   [0,1,0]])
# replicate for each farm
alerts_farms = np.stack([alerts]*3, axis=0)
bitwise_and = np.bitwise_and(alerts_farms, 1)
bitwise_or = np.bitwise_or(alerts_farms, 0)
bitwise_invert = np.invert(alerts_farms.astype(np.int8))  # careful with negatives

# -----------------------------
# 11️⃣ Arithmetic ufuncs again
add_data = np.add(normalized, 2)
sub_data = np.subtract(normalized, 1)
mul_data = np.multiply(normalized, 3)
div_data = np.divide(normalized, 2)
power_data = np.power(normalized, 2)
mod_data = np.mod(normalized, 2)

# -----------------------------
# 12️⃣ Aggregations on ufunc outputs
sum_exp = np.sum(exp_data)
mean_sin = np.mean(sin_data)

# -----------------------------
# 13️⃣ Panel totals & maintenance
panel_totals_per_farm = production_all.sum(axis=2)  # sum across hours → shape (3,4)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
print("Panel totals per farm:\n", panel_totals_per_farm)
print("Needs maintenance:", needs_maintenance)

# -----------------------------
# 14️⃣ Final KPIs
overall_total = production_all.sum()
peak_hour_value = production_all.max()
peak_idx = np.unravel_index(np.argmax(production_all), production_all.shape)  # farm, panel, hour
average_per_panel = production_all.mean(axis=2)  # shape (3,4)

print("Overall total energy:", overall_total)
print("Peak hour value:", peak_hour_value, "at farm, panel, hour:", peak_idx)
print("Average per panel:\n", average_per_panel)


Shape: (3, 4, 3)
Size: 36
Dtype: int64
Dimensions: 3
Total per farm: [150 126 165]
Mean per farm: [12.5  10.5  13.75]
Std per farm: [1.97905701 1.84842275 2.086664  ]
Var per farm: [3.91666667 3.41666667 4.35416667]
Weighted per panel:
 [[25.25 28.25 34.   27.25]
 [20.75 29.5  25.   20.  ]
 [34.   29.   25.   36.25]]


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [ ]:
import numpy as np

# -----------------------------
# 1️⃣ Create 2D arrays for each farm (panels × hours)
farmA = np.array([[10, 12, 11],
                  [9, 14, 13],
                  [15, 16, 14],
                  [11, 12, 13]])

farmB = np.array([[8, 10, 9],
                  [12, 13, 14],
                  [10, 11, 12],
                  [9, 8, 10]])

farmC = np.array([[14, 15, 16],
                  [13, 12, 14],
                  [10, 11, 12],
                  [15, 16, 17]])

# -----------------------------
# 2️⃣ Stack into 3D array (farms × panels × hours) and convert to float
production_all = np.stack([farmA, farmB, farmC], axis=0).astype(float)

# -----------------------------
# 3️⃣ Array attributes
print("Shape:", production_all.shape)
print("Size:", production_all.size)
print("Dtype:", production_all.dtype)
print("Dimensions:", production_all.ndim)

# -----------------------------
# 4️⃣ Per-farm totals and stats
total_per_farm = production_all.sum(axis=(1,2))
mean_per_farm = production_all.mean(axis=(1,2))
std_per_farm = production_all.std(axis=(1,2))
var_per_farm = production_all.var(axis=(1,2))

print("Total per farm:", total_per_farm)
print("Mean per farm:", mean_per_farm)
print("Std per farm:", std_per_farm)
print("Var per farm:", var_per_farm)

# -----------------------------
# 5️⃣ Weighted per-panel energy
hour_weights = np.array([0.5, 1.0, 0.75])  # shape (3,)
weighted_per_panel = np.dot(production_all, hour_weights)  # shape (3,4)
print("Weighted per panel:\n", weighted_per_panel)

# -----------------------------
# 6️⃣ Apply broadcasting adjustment (+0.5 kWh for Farm B)
production_all[1] += 0.5  # now works because dtype is float

# -----------------------------
# 7️⃣ Z-score normalization per farm
mean_reshaped = mean_per_farm[:, np.newaxis, np.newaxis]  # shape (3,1,1)
std_reshaped = std_per_farm[:, np.newaxis, np.newaxis]    # shape (3,1,1)

normalized = (production_all - mean_reshaped) / std_reshaped
print("Normalized shape:", normalized.shape)

# -----------------------------
# 8️⃣ Example element-wise ufuncs
exp_data = np.exp(normalized)
sin_data = np.sin(normalized)
round_data = np.round(normalized, 2)

# -----------------------------
# 9️⃣ Comparison & logical
high_output = production_all > 20
even_hours_mask = (np.arange(production_all.shape[2]) % 2 == 0)
even_hours_mask_broadcast = even_hours_mask[np.newaxis, np.newaxis, :]
logical_and_mask = np.logical_and(high_output, even_hours_mask_broadcast)

# -----------------------------
# 10️⃣ Aggregations
panel_totals_per_farm = production_all.sum(axis=2)  # sum across hours → shape (3,4)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)

overall_total = production_all.sum()
peak_hour_value = production_all.max()
peak_idx = np.unravel_index(np.argmax(production_all), production_all.shape)
average_per_panel = production_all.mean(axis=2)

# -----------------------------
# ✅ Print summary
print("\nPanel totals per farm:\n", panel_totals_per_farm)
print("Needs maintenance:", needs_maintenance)
print("Overall total energy:", overall_total)
print("Peak hour value:", peak_hour_value, "at farm, panel, hour:", peak_idx)
print("Average per panel:\n", average_per_panel)


Shape: (3, 4, 3)
Size: 36
Dtype: float64
Dimensions: 3
Total per farm: [150. 126. 165.]
Mean per farm: [12.5  10.5  13.75]
Std per farm: [1.97905701 1.84842275 2.086664  ]
Var per farm: [3.91666667 3.41666667 4.35416667]
Weighted per panel:
 [[25.25 28.25 34.   27.25]
 [20.75 29.5  25.   20.  ]
 [34.   29.   25.   36.25]]
Normalized shape: (3, 4, 3)

Panel totals per farm:
 [[33.  36.  45.  36. ]
 [28.5 40.5 34.5 28.5]
 [45.  39.  33.  48. ]]
Needs maintenance: [ True  True  True]
Overall total energy: 447.0
Peak hour value: 17.0 at farm, panel, hour: (np.int64(2), np.int64(3), np.int64(2))
Average per panel:
 [[11.  12.  15.  12. ]
 [ 9.5 13.5 11.5  9.5]
 [15.  13.  11.  16. ]]


In [ ]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Stacking and Splitting

In [ ]:
#a.Stacking
a = np.array([1,2])
b= np.array([3,4])


In [ ]:
#Vertical Stack
c = np.vstack((a,b))
d = np.hstack((a,b))

In [ ]:
print(c)
print(d)

[[1 2]
 [3 4]]
[1 2 3 4]


In [ ]:
# Splitting
split_arr = np.array([1,2,3,4,5,6])
print(np.array_split(arr,3)) #splits into  3 parts

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# Advanced Indexing

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr[arr>3])

[4 5 6]


In [ ]:
# Fancy Indexing

In [ ]:
arr = np.array([1,2,3,4,5])
indices = [1,2]
print(arr[indices])

[2 3]


In [ ]:
# Copy vs View

In [ ]:
arr = np.array([1,2,3])     # Shares the memory
view = arr.view()
view[0] = 10
print(arr)

[10  2  3]


In [ ]:
# Copy does not share memory

In [ ]:
copy = arr.copy()
copy[0] = 10
print(arr)

[10  2  3]


In [ ]:
# Saving and Loading

In [ ]:
# a. To save a file

In [ ]:
arr = np.array([1,2,3])
np.save('array.npy',arr)

In [ ]:
# b.Load the file

In [ ]:
load_arr = np.load('array.npy')
print(load_arr)

[1 2 3]


In [ ]:
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
rand_arr = np.random.random((3,3))
print(rand_arr)

[[0.36982986 0.5149527  0.52409015]
 [0.46817051 0.61750645 0.97321068]
 [0.51127773 0.17196602 0.13376594]]


In [ ]:
print("Size:",arr.size)

Size: 41


In [ ]:
print("Shape:",arr.size)

Shape: 41


In [ ]:
print("Data type:",arr.dtype)

Data type: int64


In [ ]:
print("Size:",rand_arr.size)

Size: 9


In [ ]:
print("Shape:",rand_arr.shape)

Shape: (3, 3)


In [ ]:
print("Data type:",rand_arr.dtype)

Data type: float64


In [ ]:
arr = arr+5
print(arr)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[6,7,8],[9,10,11]])

In [ ]:
print(a+b)

[[ 7  9 11]
 [13 15 17]]


In [ ]:
arr = np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(arr[0])

[1 2 3 4 5]


In [ ]:
print(arr[:,4:5])

[[ 5]
 [10]
 [15]
 [20]
 [25]]


In [ ]:
print(arr[:2,:3])

[[1 2 3]
 [6 7 8]]


In [ ]:
rand_arr = np.random.randint(10,101,size=10)

In [ ]:
print(rand_arr)

[ 93  56  42  59  75  10  37  42 100  73]


In [ ]:
print(rand_arr.max())

100


In [ ]:
print(rand_arr.min())

10


In [ ]:
print(rand_arr.mean())

58.7


In [ ]:
print(rand_arr.std())

26.000192306981116


In [ ]:
a = np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
b = a.reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr = np.array([1,2,3])

In [ ]:
k = ones + arr

In [ ]:
print(k)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [ ]:
rand = np.random.randint(1,51,size=50)
print(rand)

[ 8 17 45 38 37 27 33  9 18 27 41 38 10 26 42 23 20 34 49 13 32  4 43 18
 21 43 13 33 15 24 30  5 47  8 32 14  2 39 21 30 31 28 25 21 30 38 27 27
  9 19]


In [ ]:
l = rand%5
print(k)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [ ]:
import numpy as np

np.random.seed(0)
arr = np.random.randint(1, 51, size=20)  #
print("Original array:\n", arr)

# 2️⃣ Extract elements divisible by 5
divisible_by_5 = arr[arr % 5 == 0]
print("Elements divisible by 5:\n", divisible_by_5)


Original array:
 [45 48  1  4  4 40 10 20 22 37 24  7 25 25 13  2 39 40 24 47]
Elements divisible by 5:
 [45 40 10 20 25 25 40]


In [ ]:
a = np.array([[1,2],[4,3]])
b = np.array([[2,1],[3,4]])

In [ ]:
print(a*b)

[[ 2  2]
 [12 12]]


In [ ]:
import numpy as np

# Create a 4x4 array
arr = np.arange(1, 17).reshape(4, 4)
print("Original array:\n", arr)


Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
diagonal = arr[np.arange(4), np.arange(4)]
print("Diagonal elements:", diagonal)


Diagonal elements: [ 1  6 11 16]
